[colors.bright]
black = "0x1f1f28"
blue = "0x7AA2F7"
cyan = "0x7AA2F7"
green = "0xA9B18E"
magenta = "0x9C77B3"
red = "0xF7768E"
white = "0xDCD7BA"
yellow = "0xE0A899"

[colors.cursor]
cursor = "0xC8C093"
text = "0x1f1f28"

[colors.normal]
black = "0x1f1f28"
blue = "0x7AA2F7"
cyan = "0x7AA2F7"
green = "0xA9B18E"
magenta = "0x9C77B3"
red = "0xF7768E"
white = "0xDCD7BA"
yellow = "0xE0A899"

[colors.selection]
background = "0x1f1f28"
foreground = "0xC8C093"

[colors.primary]
background = "0x1f1f28"
foreground = "0xDCD7BA"
[font.bold]
family = "IosevkaNerdFont"
style = "Bold"

[font.bold_italic]
family = "IosevkaNerdFont"
style = "Bold Italic"

[font.italic]
family = "IosevkaNerdFont"
style = "Italic"

[font.normal]
family = "IosevkaNerdFont"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.7

[window.dimensions]
columns = 350
lines = 50

[window.padding]
x = 5
y = 5

